server:
  port: 2003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2001/eureka/
    registry-fetch-interval-seconds: 2
#    initial-instance-info-replication-interval-seconds: 3
    instance-info-replication-interval-seconds: 3
spring:
  application:
    name: myfg
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
feign:
   hystrix:
      enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#         isolation:
#            thread:
#               timeoutInMilliseconds: 6000

ribbon:
  OkToRetryOnAllOperations: true #对所有操作请求都进行重试,默认false
  ReadTimeout: 2000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000 #断路器超时时间，默认1000ms

#ribbon:
#  ConnectionTimeOut: 500
#  ReadTimeOut: 2000
#  eureka:
#    enabled: true
## Feign的断路器开启
#feign:
#  hystrix:
#    enabled: true



#ribbon:
#  eager-load:
#    enabled: true
#    clients: client1, client2, client3



