server:
  port: 2005
spring:
  application:
    name: mycore2
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ds_0
    username: root
    password: a123456
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: localhost
#    database: 0
#    port: 6379
#

  redis:
      # Redis服务器地址
      host: localhost
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接的密码（默认为空）
      password:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
eureka:
  client:
    service-url:
       defaultZone: http://localhost:2001/eureka/
    registry-fetch-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 2
    instance-info-replication-interval-seconds: 2