server:
  port: 2001
eureka:
  client:
    service-url:
       defaultZone: http://localhost:2001/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: myeureka
