server:
  port: 8005
spring:
  application:
    name: myfg8005
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
eureka:
  client:
    service-url:
          defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 13000
  ReadTimeout: 13000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
     default:
        execution:
            timeout:
                #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
                enabled: true
            isolation:
                thread:
                    timeoutInMilliseconds: 500000
myupload:
   upload-dir: f:/myupload/







