server:
  port: 8016
  max-http-header-size: 102400
  session:
    timeout: 50000
#  tomcat:
#    uri-encoding: UTF-8
spring:
  application:
    name: myfg8016
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost
    # 文件上传大小配置
    http:
        multipart:
          max-file-size: 4048Mb
          max-request-size: 4048Mb
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
eureka:
  client:
    service-url:
          defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 23000
  ReadTimeout: 23000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
     default:
        execution:
            timeout:
                #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
                enabled: true
            isolation:
                thread:
                    timeoutInMilliseconds: 500000
myupload:
   upload-dir: f:/myupload/







