server:
  port: 8006
eureka:
  client:
    service-url:
       defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
spring:
  redis:
    # Redis服务器地址
    host: localhost
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 5000
    # Redis服务器连接的密码（默认为空）
    password:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最大空闲连接
      max-idle: 8
 # 文件上传大小配置
  http:
    multipart:
      max-file-size: 4048Mb
      max-request-size: 4048Mb
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ds_0
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mycore8006
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
