server:
  port: 8006
eureka:
  client:
    service-url:
       defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ds_0
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mycore8006
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
