server:
  port: 3000
spring:
  application:
    name: myeureka_01
eureka:
  client:
    service-url:
       defaultZone: http://localhost:3000/eureka/
    register-with-eureka: false
    fetch-registry: false
