server:
  port: 10086
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
       defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: myeureka10086

